project:
  type: website
  output-dir: docs

website:
  title: "Angel Chen | 陈斯翔"
  navbar:
    right:
      - text: My Projects
        icon: flower1
        menu: 
          - text: Image Recognition
            file: projects/cat_or_dog.qmd
      - text: My blog
        icon: newspaper
        href: https://sxchen36.github.io/AngelQuartoBlog/
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css



