project:
  type: website
  output-dir: docs

website:
  title: "Angel Chen | 陈斯翔"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://username.github.io
format:
  html:
    theme: cosmo
    css: styles.css



